import { DM_Mono } from 'next/font/google';
import './globals.css';

const monoFont = DM_Mono({
	variable: '--font-mono',
	subsets: ['latin'],
	weight: ['400'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${monoFont.variable} ${monoFont.className} antialiased`}>{children}</body>
		</html>
	);
}
