import { DM_Mono, Hanken_Grotesk } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import { Link } from 'next-transition-router';
import { ActiveItemContextProvider } from '@/context/ActiveItemContextProvider';
import MainLayout from '@/components/layout/MainLayout';
import { PROJECTS } from '@/lib/constants';

const monoFont = DM_Mono({
	variable: '--font-mono',
	subsets: ['latin'],
	weight: ['400'],
});

const groteskFont = Hanken_Grotesk({
	variable: '--font-grotesk',
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${monoFont.variable} ${groteskFont.variable} ${groteskFont.className} antialiased`}>
				<MainLayout>{children}</MainLayout>
			</body>
		</html>
	);
}
